name: properties
version: 2.1.0
description: A simple library to manage properties file (and something more) in Dart
repository: https://github.com/vaind/properties.dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  meta: ^1.0.0
  test: ^1.0.0
