on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Dart ${{matrix.sdk}} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sdk: [stable, beta]

    steps:
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46 # pin@v1
        with:
          sdk: ${{ matrix.sdk }}

      - uses: actions/checkout@v3

      - run: dart pub get

      - run: dart test

      - run: dart analyze
